name = "Faulis Vanilla +"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e6a47fd3f2d070f2c3299b467d797c79f7aa3eb0eabdd8650098a0b04187085"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
