name = "Faulis Vanilla +"
author = "Fauli1221"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4e7dfa44b36b36b9c2dcd292beec2827612b6f00153e9b7791c1c0d41bf15724"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"

[options]
acceptable-game-versions = "1.18"
no-internal-hashes = false
