name = "HD Skins"
filename = "hdskins-6.5.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/FzE9gshV/versions/6.5.2/hdskins-6.5.2.jar"
hash-format = "sha1"
hash = "6751843792bcdd6032a0722d6fa3ad3e53b404b7"

[update]
[update.modrinth]
mod-id = "FzE9gshV"
version = "O5qwHu2G"

[option]
optional = true
description = "Adds a custom skin server with HD-Skin support Recomendet with MineLittlePony"
default = true
